version: '3.8'

services:
  myapi:
    image: b4/peppol-service/ppa
    build:
      context: ./MyApi
      dockerfile: Dockerfile
    ports:
      - "8000:80"

  nginx:
    image: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - myapi